# Generated by Django 4.1.6 on 2023-02-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('wordpair', models.CharField(max_length=255)),
            ],
        ),
    ]
