# Generated by Django 4.1.6 on 2023-02-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpair_app', '0002_rename_wordpair_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
