# Generated by Django 4.1.6 on 2023-02-14 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wordpair_app', '0003_alter_word_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='first_word',
        ),
        migrations.AddField(
            model_name='word',
            name='second_word',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
